# Generated by Django 2.2.10 on 2020-11-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=500)),
                ('img_file', models.ImageField(default='default.jpg', upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Authorities',
        ),
        migrations.DeleteModel(
            name='BlockAtGlance',
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
        migrations.DeleteModel(
            name='PublicUtilities',
        ),
    ]
