# Generated by Django 2.2.10 on 2020-11-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201129_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsection',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='mainsection',
            name='img_file',
            field=models.ImageField(default='logo.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='mainsection',
            name='img_name',
            field=models.CharField(max_length=20),
        ),
    ]
