# Generated by Django 2.2.10 on 2020-11-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201129_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=20)),
                ('img_file', models.ImageField(default='logo.jpg', upload_to='images/')),
                ('description', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.RenameModel(
            old_name='PublicUtilities',
            new_name='Utilities',
        ),
        migrations.DeleteModel(
            name='Authorities',
        ),
        migrations.DeleteModel(
            name='BlockAtGlance',
        ),
    ]
