# Generated by Django 2.2.10 on 2020-11-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201129_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='img_file',
        ),
        migrations.AddField(
            model_name='sample',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sample',
            name='contact_no',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='sample',
            name='email',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sample',
            name='name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
